services:
  strapi-prod:
    container_name: strapi
    build:
      context: CMS
      dockerfile: ../deployment/strapi/Dockerfile.production
    image: strapi:latest
    restart: unless-stopped
    env_file: CMS/.env
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      #- ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: jfrog.apa-techs.com/docker/postgres:latest
    env_file: CMS/.env
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
    ports:
      - "5432:5432"

  ui:
    container_name: strapi-ui
    platform: linux/amd64
    restart: unless-stopped
    #image: strapi-ui:latest
    build:
      context: UI
      dockerfile: ../deployment/ui/Dockerfile
    volumes:
      #- UI/dist/ui:/usr/share/nginx/html
      - ./deployment/ui/conf.d:/etc/nginx/conf.d/
    ports:
      - "80:80"

volumes:
  strapi-data:

